apiVersion: batch/v1
kind: CronJob
metadata:
  name: extract-load
  namespace: ticket-trackr
spec:
  schedule: "0 0 * * *"  # Runs every day at midnight
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: shared-data
            persistentVolumeClaim:
              claimName: data-pvc
          initContainers:
          - name: extract-emails
            image: mimove/tickettrackr-extract-load:latest
            imagePullPolicy: Always
            volumeMounts:
            - name: shared-data
              mountPath: /data
            env:
            - name: REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cli-env
                  key: REFRESH_TOKEN
            - name: SENDER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: cli-env
                  key: SENDER_EMAIL
            - name: GMAIL_CLIENT_SECRET_PATH
              valueFrom:
                secretKeyRef:
                  name: cli-env
                  key: GMAIL_CLIENT_SECRET_PATH
            - name: GMAIL_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: cli-env
                  key: GMAIL_CLIENT_SECRET
            - name: SAVE_DIR
              value: "/data/gmail_tickets_extraction/emails"
            command: ["python3", "cli.py", "--extract_tickets_from_gmail"]
          - name: convert-to-avro
            image: mimove/tickettrackr-extract-load:latest
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - name: shared-data
              mountPath: /data
            env:
            - name: SAVE_DIR
              value: "/data/gmail_tickets_extraction/emails"
            command: ["python3", "cli.py", "--convert_pdf_to_avro"]
          containers:
          - name: dummy-container
            image: alpine
            command: ["echo", "Job finished"]
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: regcred