apiVersion: batch/v1
kind: CronJob
metadata:
  name: extract-load
  namespace: ticket-trackr
spec:
  schedule: "0 0 * * *" # Schedule to run every day at midnight
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
          - name: regcred
          containers:
          - name: extract-emails
            image: mimove/tickettrackr-extract-load:latest
            imagePullPolicy: Always
            command: ["sh", "-c", "python3 cli.py --extract_tickets_from_gmail"]
            env:
            - name: SYNOLOGY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cli-env
                  key: SYNOLOGY_PASSWORD
            - name: SYNOLOGY_PORT
              valueFrom:
                secretKeyRef:
                  name: cli-env
                  key: SYNOLOGY_PORT
            - name: SYNOLOGY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cli-env
                  key: SYNOLOGY_USERNAME
            - name: GMAIL_CLIENT_SECRET_PATH
              valueFrom:
                secretKeyRef:
                  name: cli-env
                  key: GMAIL_CLIENT_SECRET_PATH
            - name: GMAIL_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: cli-env
                  key: GMAIL_CLIENT_SECRET
            - name: SAVE_DIR
              valueFrom:
                secretKeyRef:
                  name: cli-env
                  key: SAVE_DIR
            - name: SYNOLOGY_IP
              valueFrom:
                secretKeyRef:
                  name: cli-env
                  key: SYNOLOGY_IP
            - name: REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cli-env
                  key: REFRESH_TOKEN
            - name: SENDER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: cli-env
                  key: SENDER_EMAIL
            - name: SYNOLOGY_DIRECTORY
              valueFrom:
                secretKeyRef:
                  name: cli-env
                  key: SYNOLOGY_DIRECTORY
            resources:
              requests:
                memory: "256Mi"
                cpu: "500m"
              limits:
                memory: "512Mi"
                cpu: "1000m"
          restartPolicy: OnFailure
