apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-extract-load
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/
