name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Start environment
        run: make env-start

      - name: Install test requirements
        run: make install-test-requirements

      - name: Run linting
        run: make ci-linting

      - name: Run tests
        run: make ci-test

      - name: Stop environment
        if: always()
        run: make env-stop

      - name: Clean up Docker
        if: always()
        run: make docker-cleanup
